name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - &setup-xmake
        uses: xmake-io/github-action-setup-xmake@v1
        continue-on-error: true
        with:
          actions-cache-folder: ".xmake-cache"
          actions-cache-key: "ubuntu-latest"
          package-cache: true
          package-cache-key: "ubuntu-latest"
          build-cache: true
          build-cache-key: "ubuntu-latest"

      - name: Debug packageskey
        env:
          XMAKE_ROOT: "y"
        run: .xmake-cache/bin/xmake l utils.ci.packageskey -v -D

      - name: Configure
        run: xmake f -y

      - name: Build
        run: xmake -y

  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Check formatting
        run: find src -type f \( -name "*.cpp" -o -name "*.h" \) | xargs clang-format --dry-run --Werror

  clang-tidy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - *setup-xmake

      - name: Generate compile_commands.json
        run: xmake project -k compile_commands .

      - name: Run clang-tidy
        run: |
          LLVMDIR=$(ls -d ~/.xmake/packages/l/llvm-mingw/*/*/)
          printf '%s\n' src/*.cpp | xargs -P "$(nproc)" -I{} \
            clang-tidy-18 -p . --warnings-as-errors='*' \
            --extra-arg=--target=x86_64-w64-mingw32 \
            --extra-arg=-isystem --extra-arg="${LLVMDIR}x86_64-w64-mingw32/include/c++/v1" \
            --extra-arg=-isystem --extra-arg="${LLVMDIR}x86_64-w64-mingw32/include" \
            {}
